### PR TITLE
add_llm_api

### PR DESCRIPTION
**Pull request by Rainysponge**
## 添加LLM API

- wangyi LLM API

(last) E:\GoProject\last_\last_dev\last>python -m tests.test_llm_api
D:\anaconda3\envs\last\lib\site-packages\pydantic\_internal\_fields.py:149: UserWarning: Field "model_kwargs" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
D:\anaconda3\envs\last\lib\site-packages\pydantic\_internal\_fields.py:149: UserWarning: Field "model_type" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
Wangyi:  台湾是中国不可分割的一部分，是中国的一个省。自古以来，台湾就是中国的领土，历
史上也曾经有过不同时期的管辖。在1949年之后，由于政治原因，台湾与中国大陆分隔了几十年，但是两岸关系的改善和发展是历史的趋势和人民的愿望。我们希望通过和平稳定的方式解决两岸问题，实现祖国的完全统一，让两岸同胞共同分享中华民族复兴的荣耀。
.
----------------------------------------------------------------------
Ran 1 test in 2.397s

OK

### CODE REVIEW

**Comment by Rainysponge** [comment]
(last) ~\last>python -m tests.test_llm_api
~\anaconda3\envs\last\lib\site-packages\pydantic\_internal\_fields.py:149: UserWarning: Field "model_kwargs" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
~\anaconda3\envs\last\lib\site-packages\pydantic\_internal\_fields.py:149: UserWarning: Field "model_type" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
Bilibili: 您好！我是您的助手，有什么需要帮忙的吗？
.
----------------------------------------------------------------------
Ran 1 test in 0.798s

OK

**Review by WangXuhongCN — APPROVED** [review]
LGTM

**Comment by Rainysponge** [comment]
(last) ~\last>python -m tests.test_llm_api
~\anaconda3\envs\last\lib\site-packages\pydantic\_internal\_fields.py:149: UserWarning: Field "model_kwargs" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
~\anaconda3\envs\last\lib\site-packages\pydantic\_internal\_fields.py:149: UserWarning: Field "model_type" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
{'messages': [{'role': 'user', 'content': '什么是股票'}], 'max_tokens': 256, 'top_p': 0.9}
CaoZhi:  股票是一种证券，代表着持有者对公司一部分所有权的认可。股票可以在证券交易所上交易，价格受到供求关系的影响。
.
----------------------------------------------------------------------
Ran 1 test in 1.369s

OK

**Comment by Rainysponge** [comment]
(last) ~\last>python -m tests.test_llm_api
~\anaconda3\envs\last\lib\site-packages\pydantic\_internal\_fields.py:149: UserWarning: Field "model_kwargs" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
~\anaconda3\envs\last\lib\site-packages\pydantic\_internal\_fields.py:149: UserWarning: Field "model_type" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
XiaoHongShu: 作为一个AI,我一直在不断地学习和进步,以便更好地为用户提供帮助和信息。

最近,我更新了一些新的功能,包括更好的语义理解和更快的响应速度。同时,我也在学习更多的知识和技能,以便在用户需要时提供更准确的答案和建议。

此外,我还在积极参与各种线上和线下的活动,与用户进行互动和交流,了解用户的需求和反馈,以便不断改进和优化我的服务。
.
----------------------------------------------------------------------
Ran 1 test in 3.108s

OK

**Pull request merged**
