### PR TITLE
add easymoney api

### PR DESCRIPTION
**Pull request by Rainysponge**
## 简单描述
添加东方财富大模型——奇思妙想API

### 一次成功的运行

(last) roote@MYPC:~/last$ python -m tests.test_llm_api
~/anaconda3/envs/last/lib/python3.8/site-packages/pydantic/_internal/_fields.py:128: UserWarning: Field "model_kwargs" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
~/anaconda3/envs/last/lib/python3.8/site-packages/pydantic/_internal/_fields.py:128: UserWarning: Field "model_type" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
{'code': 0, 'message': None, 'data': ' 谢谢!作为一款人工智能助手,我没有生日这一概念,但我很高兴能为您提供帮助和信息。请问有什么我可以帮助您的吗?', 'requestId': '0da075f6-bdfd-4ed2-9174-236d14e5489c', 'costTime': '1191', 'success': True}
EasyMoney:  谢谢!作为一款人工智能助手,我没有生日这一概念,但我很高兴能为您提供帮助和信息。请问有什么我可以帮助您的吗?
.
----------------------------------------------------------------------
Ran 1 test in 11.519s

OK

### 使用错误的key

(last) roote@MYPC:~/last$ python -m tests.test_llm_api
~/anaconda3/envs/last/lib/python3.8/site-packages/pydantic/_internal/_fields.py:128: UserWarning: Field "model_kwargs" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
~/anaconda3/envs/last/lib/python3.8/site-packages/pydantic/_internal/_fields.py:128: UserWarning: Field "model_type" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
{'code': -3, 'message': 'token验证失败', 'data': None, 'requestId': '7650e0c7-12de-43c8-9b63-f3284d5497d4', 'costTime': '1', 'success': False}

[Error] Exception: An error occured!
[Response] {'code': -3, 'message': 'token验证失败', 'data': None, 'requestId': '7650e0c7-12de-43c8-9b63-f3284d5497d4', 'costTime': '1', 'success': False}

### CODE REVIEW

**Comment by Rainysponge** [comment]
(last) root@MyPC:~/last$ python -m tests.test_llm_api
~/anaconda3/envs/last/lib/python3.8/site-packages/pydantic/_internal/_fields.py:128: UserWarning: Field "model_kwargs" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
~/anaconda3/envs/last/lib/python3.8/site-packages/pydantic/_internal/_fields.py:128: UserWarning: Field "model_type" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.

  warnings.warn()

HuaZang: 最近我在学习如何更好地为人类提供服务，并不断改进自己的回答能力。
（本内容由华藏大模型提供AI生成服务）
.
----------------------------------------------------------------------
Ran 1 test in 2.872s

OK

**Comment by Rainysponge** [comment]
(last) root@MyPC:~/last$ python -m tests.test_llm_api
~/envs/last/lib/python3.8/site-packages/pydantic/_internal/_fields.py:128: UserWarning: Field "model_kwargs" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
~/anaconda3/envs/last/lib/python3.8/site-packages/pydantic/_internal/_fields.py:128: UserWarning: Field "model_type" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
KKBot: 竹海: 作为竹海AI模型，我的任务是为用户提供日常生活相关问题的解答。最近在做什么呀，这个问题的答案
.HuaZang: 最近我在学习如何更好地为人类提供服务，并不断改进自己的回答能力。
（本内容由华藏大模型提供AI生成服务）
.
----------------------------------------------------------------------
Ran 2 tests in 27.872s

OK

**Comment by Rainysponge** [comment]
base model不改KKBOT好像不太行 他回复的消息格式如下：
'''
data: {}

data: {}

data: {}
'''

**Comment by Rainysponge** [comment]
os.environ["KKBOT_API_TOKEN"] = 对于kkbot的os需要设置成字典：
'{"api_key": "xxx", "userId":"xx", "appId":"xxx", "sessionId":"xxx"}

**Review by WangXuhongCN — APPROVED** [review]
LGTM

**Pull request merged**
